java.lang.NoSuchFieldError: Class jakarta.persistence.GenerationType does not have member field 'jakarta.persistence.GenerationType UUID' persists. fixed some pom.xml dependencies to match versions.